version: '3.8'
services:
  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DB_PATH=/app/data/storefront.db
      - PAYMENT_BASE_URL=http://payment:8080
      - LOG_PATH=/app/logs/storefront.log
      # Uncomment and set YOUR_APM_TOKEN for APM tracing
      # - OTEL_SERVICE_NAME=storefront
      # - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev,service.version=0.1.0
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # - OTEL_EXPORTER_OTLP_ENDPOINT=https://trace-ingestion.eu-frankfurt-1.oci.oraclecloud.com/20200101/opentelemetry/v1/traces
      # - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer YOUR_APM_TOKEN
    volumes:
      - ./storefront/data:/app/data
      - ./storefront/logs:/app/logs
    depends_on:
      - payment

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - LOG_PATH=/app/logs/payment.log
      # Uncomment and set YOUR_APM_TOKEN for APM tracing
      # - OTEL_SERVICE_NAME=payment
      # - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev,service.version=0.1.0
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # - OTEL_EXPORTER_OTLP_ENDPOINT=https://trace-ingestion.eu-frankfurt-1.oci.oraclecloud.com/20200101/opentelemetry/v1/traces
      # - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer YOUR_APM_TOKEN
    volumes:
      - ./payment/logs:/app/logs
